email:             your-email@example.com
author:            AgroClim project members
baseurl:           ""
url:               "http://agroclim-huaraz.info"

# Language stuff
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]

# Social Profiles
twitter_username:
github_username:   agroclim-huaraz
facebook_username:

# Build settings
markdown:          kramdown
paginate:          20
paginate_path:     "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
