title:             AgroClim Huaraz
email:             your-email@example.com
description:       A research proposal submitted to the Austrian Academy of Sciences
author:            AgroClim project members
baseurl:           ""
url:               "http://agroclim-huaraz.info"

# Social Profiles
twitter_username:
github_username:   agroclim-huaraz
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
